### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by Verkla** [skoniks/exmanga-ext#11]
Есть вариант собрать билд под Firefox? 
Очень нужно)

**Comment by skoniks** [comment]
Есть же расширения для Firefox, которые позволяют ставить расширения их хрома. Сам просто мозиллой не пользуюсь, не уверен что найду время разобраться, а тем более поддерживать. Но как говориться пулл реквестам всегда рад.

**Comment by Verkla** [comment]
> Есть же расширения для Firefox, которые позволяют ставить расширения их хрома.

Оно уже, к сожалению, не ликвид. Способа сейчас поставить расширение на лису я не нашел (хотя вроде обыскал все).

> Но как говориться пулл реквестам всегда рад.

Сам бы с радостью сделал, но тоже особо времени разобраться нет, вроде там система похожая, только манифест чутка поправить и chrome на browser свануть (только то что я знаю). В остальном хз, мб кто разберется. Но если желание и время появится, буду только рад, ибо хромиумом вообще не пользуюсь

**Comment by skoniks** [comment]
> > Есть же расширения для Firefox, которые позволяют ставить расширения их хрома.
> 
> Оно уже, к сожалению, не ликвид. Способа сейчас поставить расширение на лису я не нашел (хотя вроде обыскал все).
> 
> > Но как говориться пулл реквестам всегда рад.
> 
> Сам бы с радостью сделал, но тоже особо времени разобраться нет, вроде там система похожая, только манифест чутка поправить и chrome на browser свапнуть (только то что я знаю). В остальном хз, мб кто разберется. Но если желание и время появится, буду только рад, ибо хромиумом вообще не пользуюсь

Ну собственно как человек у которого не установлен firefox мало чем могу помочь.
