### ISSUE TITLE
Не открываются главы

### ISSUE THREAD

**Issue by RedCapcha** [skoniks/exmanga-ext#15]
Пишет что глава загружена с сервера, но изображения не появляются. Позавчера такой проблемы не было, переустановка расширения не помогла.

**Comment by skoniks** [comment]
> Пишет что глава загружена с сервера, но изображения не появляются. Позавчера такой проблемы не было, переустановка расширения не помогла.

Со стороны реманги была добавлена новая защита, решим проблему к версии 3.11
