### ISSUE TITLE
Низкое разрешение скаченных глав. 

### ISSUE THREAD

**Issue by kiozet** [skoniks/exmanga-ext#18]
Во-первых, спасибо! Расширение прекрасное, но столкнулся с проблемой низкого разрешения глав скаченных с сервера. 1-ый скрин - слитая глава, второй - не слитая, в бесплатном доступе. 
![image](https://user-images.githubusercontent.com/64327953/231180347-e9e6777a-8b05-4cc8-a923-31a5ea0ecc84.png)
![image](https://user-images.githubusercontent.com/64327953/231180501-f7bba87c-f578-4949-a997-b334be1fc19f.png)

**Comment by kiozet** [comment]
![image](https://user-images.githubusercontent.com/64327953/231182973-2583686e-7064-46a1-b4a5-6cf246361a88.png)

**Comment by skoniks** [comment]
Мы не режем качество изображений. О какой именно главе идет речь?
