### ISSUE TITLE
Некорректный порядок отображения страниц

### ISSUE THREAD

**Issue by IIeJImewek** [skoniks/exmanga-ext#19]
Для сравнения главы из тайтла. Слева направо.

1. Купил на реманге
2. Загрузил с сервера exmanga

<img width="1280" alt="Screenshot_10" src="https://github.com/skoniks/exmanga-ext/assets/47460147/8308a9f8-fd84-407d-a245-59ff1859785f">

**Comment by skoniks** [comment]
Какая манга, какая глава? Скорее всего в расширение просто загрузили главу с ошибкой, а переводчики потом исправили. Если я ее удалю, а ты заново откроешь - проблема исправиться. Это не проблема самого расширения, по таким вопросам лучше писать к нам в беседу - [https://t.me/+87MOSlV7tV02MjUy](https://t.me/+87MOSlV7tV02MjUy)

**Comment by skoniks** [comment]
> 179 глава "Как демон император стал дворецким". На самом деле таких глав больше 20, но где конкретно начинается нарушаться порядок - не помню.

Перезалил все главы, они были битыми изначально от переводчиков, но со временем те пофиксили.
