### ISSUE TITLE
Баги атакуют

### ISSUE THREAD

**Issue by RedCapcha** [skoniks/exmanga-ext#21]
Появился баг удаляющий все прогруженные изображения после загрузки последнего фрейма.

![photo_2023-07-10_14-38-41](https://github.com/skoniks/exmanga-ext/assets/78724563/aed2956f-8620-4780-9b85-09fdef41823c)

**Comment by skoniks** [comment]
> Появился баг удаляющий все прогруженные изображения после загрузки последнего фрейма.
> 
> ![photo_2023-07-10_14-38-41](https://user-images.githubusercontent.com/78724563/252327497-aed2956f-8620-4780-9b85-09fdef41823c.jpg)

На любой главе, или только на платных?

**Comment by skoniks** [comment]
Приложите скрин консоли, со страницы на которой возникает ошибка. 

![image](https://github.com/skoniks/exmanga-ext/assets/13507597/f38e7062-d33c-49fb-ad35-3369507b200b)

**Comment by skoniks** [comment]
Скорее всего был баг самой реманги, поскольку расширение не влияет на контекст страницы, а только подменяет данные открываемой главы манги.
